[package]
name = "top-g-simulator"
version = "0.1.0"
edition = "2021"
description = "Spend just a few moments in the life of the TOP G"

[dependencies]
bevy= "0.11.0"
rand = "0.8.5"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
